---
title: "Logistic GLM Companies R"
author: "Cory Suzuki"
date: "2024-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(rcompanion)
library(MASS)
```

```{r}
#Import the data
companies_data = read.csv(file="./Example3.1Data.csv", header=T, sep=",")

#Specify reference categories
ownership = as.factor(companies_data$ownership)
approach = as.factor(companies_data$approach)
ownership_rel = relevel(ownership, ref="partner")
approach_rel = relevel(approach, ref="comp")
```

```{r}
fitted_model = glm(approach_rel~ownership_rel+nemployees,
                   data=companies_data, family=binomial(link=logit))
summary(fitted_model)
```

```{r}
#Extracting AIC and BIC for fitted logit model
p=4
n=50
AIC = -2*logLik(fitted_model)+2*p*n/(n-p-1)
print(AIC)
BIC(fitted_model)
```
```{r}
#Checking model fit
intercept_only_mod = glm(approach_rel~1,
                         family=binomial(link=logit))
deviance = -2*(logLik(intercept_only_mod)-logLik(fitted_model))
print(deviance)
```

```{r}
p_value = pchisq(deviance, df=3, lower.tail=F)
print(p_value)
```

```{r}
#Using fitted model for prediction
print(predict(fitted_model, type="response",
              data.frame(ownership_rel="sole", nemployees=40)))
```
